// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\lms\lms_pcore_src_LMS_Filter.v
// Created: 2026-06-05 20:55:49
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: lms_pcore_src_LMS_Filter
// Source Path: lms/LMS/LMS Filter
// Hierarchy Level: 1
// Model version: 1.9
// 
// LMS Filter: LMS Algorithm
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module lms_pcore_src_LMS_Filter
          (clk,
           reset,
           enb,
           lms_input,
           lms_desired,
           lms_error);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] lms_input;  // sfix16_En14
  input   signed [15:0] lms_desired;  // sfix16_En14
  output  signed [15:0] lms_error;  // sfix16_En14


  reg signed [15:0] temp_process1_reg [0:14];  // sfix16 [15]
  reg signed [15:0] temp_process1_reg_next [0:14];  // sfix16_En14 [15]
  reg signed [15:0] data_pipeline [0:15];  // sfix16_En14 [16]
  wire signed [15:0] data_pipeline_0;  // sfix16_En14
  wire signed [15:0] data_pipeline_0_1;  // sfix16_En14
  wire signed [15:0] C_LMS_FILTER_STEP_SIZE;  // sfix16_En17
  wire signed [15:0] data_pipeline_1;  // sfix16_En14
  wire signed [15:0] data_pipeline_2;  // sfix16_En14
  wire signed [15:0] data_pipeline_3;  // sfix16_En14
  wire signed [15:0] data_pipeline_4;  // sfix16_En14
  wire signed [15:0] data_pipeline_5;  // sfix16_En14
  wire signed [15:0] data_pipeline_6;  // sfix16_En14
  wire signed [15:0] data_pipeline_7;  // sfix16_En14
  wire signed [15:0] data_pipeline_8;  // sfix16_En14
  wire signed [15:0] data_pipeline_9;  // sfix16_En14
  wire signed [15:0] data_pipeline_10;  // sfix16_En14
  wire signed [15:0] data_pipeline_11;  // sfix16_En14
  wire signed [15:0] data_pipeline_12;  // sfix16_En14
  wire signed [15:0] data_pipeline_13;  // sfix16_En14
  wire signed [15:0] data_pipeline_14;  // sfix16_En14
  wire signed [15:0] data_pipeline_15;  // sfix16_En14
  wire signed [15:0] data_pipeline_1_1;  // sfix16_En14
  wire signed [15:0] data_pipeline_2_1;  // sfix16_En14
  wire signed [15:0] data_pipeline_3_1;  // sfix16_En14
  wire signed [15:0] data_pipeline_4_1;  // sfix16_En14
  wire signed [15:0] data_pipeline_5_1;  // sfix16_En14
  wire signed [15:0] data_pipeline_6_1;  // sfix16_En14
  wire signed [15:0] data_pipeline_7_1;  // sfix16_En14
  wire signed [15:0] data_pipeline_8_1;  // sfix16_En14
  wire signed [15:0] data_pipeline_9_1;  // sfix16_En14
  wire signed [15:0] data_pipeline_10_1;  // sfix16_En14
  wire signed [15:0] data_pipeline_11_1;  // sfix16_En14
  wire signed [15:0] data_pipeline_12_1;  // sfix16_En14
  wire signed [15:0] data_pipeline_13_1;  // sfix16_En14
  wire signed [15:0] data_pipeline_14_1;  // sfix16_En14
  wire signed [15:0] data_pipeline_15_1;  // sfix16_En14
  reg signed [15:0] weight [0:15];  // sfix16_En14 [16]
  wire signed [15:0] weight_15;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp;  // sfix32_En28
  wire signed [15:0] filter_products_15;  // sfix16_En14
  wire signed [15:0] weight_14;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_1;  // sfix32_En28
  wire signed [15:0] filter_products_14;  // sfix16_En14
  wire signed [15:0] weight_13;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_2;  // sfix32_En28
  wire signed [15:0] filter_products_13;  // sfix16_En14
  wire signed [15:0] weight_12;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_3;  // sfix32_En28
  wire signed [15:0] filter_products_12;  // sfix16_En14
  wire signed [15:0] weight_11;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_4;  // sfix32_En28
  wire signed [15:0] filter_products_11;  // sfix16_En14
  wire signed [15:0] weight_10;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_5;  // sfix32_En28
  wire signed [15:0] filter_products_10;  // sfix16_En14
  wire signed [15:0] weight_9;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_6;  // sfix32_En28
  wire signed [15:0] filter_products_9;  // sfix16_En14
  wire signed [15:0] weight_8;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_7;  // sfix32_En28
  wire signed [15:0] filter_products_8;  // sfix16_En14
  wire signed [15:0] weight_7;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_8;  // sfix32_En28
  wire signed [15:0] filter_products_7;  // sfix16_En14
  wire signed [15:0] weight_6;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_9;  // sfix32_En28
  wire signed [15:0] filter_products_6;  // sfix16_En14
  wire signed [15:0] weight_5;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_10;  // sfix32_En28
  wire signed [15:0] filter_products_5;  // sfix16_En14
  wire signed [15:0] weight_4;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_11;  // sfix32_En28
  wire signed [15:0] filter_products_4;  // sfix16_En14
  wire signed [15:0] weight_3;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_12;  // sfix32_En28
  wire signed [15:0] filter_products_3;  // sfix16_En14
  wire signed [15:0] weight_2;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_13;  // sfix32_En28
  wire signed [15:0] filter_products_2;  // sfix16_En14
  wire signed [15:0] weight_1;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_14;  // sfix32_En28
  wire signed [15:0] filter_products_1;  // sfix16_En14
  wire signed [15:0] mu_err;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_15;  // sfix32_En28
  wire signed [15:0] mu_err_data_prod_15;  // sfix16_En14
  wire signed [15:0] weight_15_1;  // sfix16_En14
  wire signed [15:0] weight_adder_output_15;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_16;  // sfix32_En28
  wire signed [15:0] mu_err_data_prod_14;  // sfix16_En14
  wire signed [15:0] weight_14_1;  // sfix16_En14
  wire signed [15:0] weight_adder_output_14;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_17;  // sfix32_En28
  wire signed [15:0] mu_err_data_prod_13;  // sfix16_En14
  wire signed [15:0] weight_13_1;  // sfix16_En14
  wire signed [15:0] weight_adder_output_13;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_18;  // sfix32_En28
  wire signed [15:0] mu_err_data_prod_12;  // sfix16_En14
  wire signed [15:0] weight_12_1;  // sfix16_En14
  wire signed [15:0] weight_adder_output_12;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_19;  // sfix32_En28
  wire signed [15:0] mu_err_data_prod_11;  // sfix16_En14
  wire signed [15:0] weight_11_1;  // sfix16_En14
  wire signed [15:0] weight_adder_output_11;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_20;  // sfix32_En28
  wire signed [15:0] mu_err_data_prod_10;  // sfix16_En14
  wire signed [15:0] weight_10_1;  // sfix16_En14
  wire signed [15:0] weight_adder_output_10;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_21;  // sfix32_En28
  wire signed [15:0] mu_err_data_prod_9;  // sfix16_En14
  wire signed [15:0] weight_9_1;  // sfix16_En14
  wire signed [15:0] weight_adder_output_9;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_22;  // sfix32_En28
  wire signed [15:0] mu_err_data_prod_8;  // sfix16_En14
  wire signed [15:0] weight_8_1;  // sfix16_En14
  wire signed [15:0] weight_adder_output_8;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_23;  // sfix32_En28
  wire signed [15:0] mu_err_data_prod_7;  // sfix16_En14
  wire signed [15:0] weight_7_1;  // sfix16_En14
  wire signed [15:0] weight_adder_output_7;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_24;  // sfix32_En28
  wire signed [15:0] mu_err_data_prod_6;  // sfix16_En14
  wire signed [15:0] weight_6_1;  // sfix16_En14
  wire signed [15:0] weight_adder_output_6;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_25;  // sfix32_En28
  wire signed [15:0] mu_err_data_prod_5;  // sfix16_En14
  wire signed [15:0] weight_5_1;  // sfix16_En14
  wire signed [15:0] weight_adder_output_5;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_26;  // sfix32_En28
  wire signed [15:0] mu_err_data_prod_4;  // sfix16_En14
  wire signed [15:0] weight_4_1;  // sfix16_En14
  wire signed [15:0] weight_adder_output_4;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_27;  // sfix32_En28
  wire signed [15:0] mu_err_data_prod_3;  // sfix16_En14
  wire signed [15:0] weight_3_1;  // sfix16_En14
  wire signed [15:0] weight_adder_output_3;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_28;  // sfix32_En28
  wire signed [15:0] mu_err_data_prod_2;  // sfix16_En14
  wire signed [15:0] weight_2_1;  // sfix16_En14
  wire signed [15:0] weight_adder_output_2;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_29;  // sfix32_En28
  wire signed [15:0] mu_err_data_prod_1;  // sfix16_En14
  wire signed [15:0] weight_1_1;  // sfix16_En14
  wire signed [15:0] weight_adder_output_1;  // sfix16_En14
  wire signed [15:0] filter_error_sub_accum;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_30;  // sfix32_En31
  wire signed [31:0] multiplier_mul_temp_31;  // sfix32_En28
  wire signed [15:0] mu_err_data_prod_0;  // sfix16_En14
  wire signed [15:0] weight_0;  // sfix16_En14
  wire signed [15:0] weight_adder_output_0;  // sfix16_En14
  wire signed [15:0] weight_adder_output [0:15];  // sfix16_En14 [16]
  wire signed [15:0] weight_0_1;  // sfix16_En14
  wire signed [31:0] multiplier_mul_temp_32;  // sfix32_En28
  wire signed [15:0] filter_products_0;  // sfix16_En14
  wire signed [15:0] fir_add_stage2_add_temp;  // sfix16_En14
  wire signed [16:0] fir_add_op_stage1;  // sfix17_En14
  wire signed [15:0] fir_add_stage3_add_cast;  // sfix16_En14
  wire signed [15:0] fir_add_stage3_add_temp;  // sfix16_En14
  wire signed [17:0] fir_add_op_stage2;  // sfix18_En14
  wire signed [15:0] fir_add_stage4_add_cast;  // sfix16_En14
  wire signed [15:0] fir_add_stage4_add_temp;  // sfix16_En14
  wire signed [18:0] fir_add_op_stage3;  // sfix19_En14
  wire signed [15:0] fir_add_stage5_add_cast;  // sfix16_En14
  wire signed [15:0] fir_add_stage5_add_temp;  // sfix16_En14
  wire signed [19:0] fir_add_op_stage4;  // sfix20_En14
  wire signed [15:0] fir_add_stage6_add_cast;  // sfix16_En14
  wire signed [15:0] fir_add_stage6_add_temp;  // sfix16_En14
  wire signed [20:0] fir_add_op_stage5;  // sfix21_En14
  wire signed [15:0] fir_add_stage7_add_cast;  // sfix16_En14
  wire signed [15:0] fir_add_stage7_add_temp;  // sfix16_En14
  wire signed [21:0] fir_add_op_stage6;  // sfix22_En14
  wire signed [15:0] fir_add_stage8_add_cast;  // sfix16_En14
  wire signed [15:0] fir_add_stage8_add_temp;  // sfix16_En14
  wire signed [22:0] fir_add_op_stage7;  // sfix23_En14
  wire signed [15:0] fir_add_stage9_add_cast;  // sfix16_En14
  wire signed [15:0] fir_add_stage9_add_temp;  // sfix16_En14
  wire signed [23:0] fir_add_op_stage8;  // sfix24_En14
  wire signed [15:0] fir_add_stage10_add_cast;  // sfix16_En14
  wire signed [15:0] fir_add_stage10_add_temp;  // sfix16_En14
  wire signed [24:0] fir_add_op_stage9;  // sfix25_En14
  wire signed [15:0] fir_add_stage11_add_cast;  // sfix16_En14
  wire signed [15:0] fir_add_stage11_add_temp;  // sfix16_En14
  wire signed [25:0] fir_add_op_stage10;  // sfix26_En14
  wire signed [15:0] fir_add_stage12_add_cast;  // sfix16_En14
  wire signed [15:0] fir_add_stage12_add_temp;  // sfix16_En14
  wire signed [26:0] fir_add_op_stage11;  // sfix27_En14
  wire signed [15:0] fir_add_stage13_add_cast;  // sfix16_En14
  wire signed [15:0] fir_add_stage13_add_temp;  // sfix16_En14
  wire signed [27:0] fir_add_op_stage12;  // sfix28_En14
  wire signed [15:0] fir_add_stage14_add_cast;  // sfix16_En14
  wire signed [15:0] fir_add_stage14_add_temp;  // sfix16_En14
  wire signed [28:0] fir_add_op_stage13;  // sfix29_En14
  wire signed [15:0] fir_add_stage15_add_cast;  // sfix16_En14
  wire signed [15:0] fir_add_stage15_add_temp;  // sfix16_En14
  wire signed [29:0] fir_add_op_stage14;  // sfix30_En14
  wire signed [15:0] fir_add_stage16_add_cast;  // sfix16_En14
  wire signed [15:0] filter_sum;  // sfix16_En14
  reg signed [31:0] temp_process1_t_0_0;  // int32
  reg signed [31:0] temp_process1_t_1;  // int32
  reg signed [31:0] temp_process1_t_0_1;  // int32
  reg signed [31:0] temp_process1_t_1_0;  // int32
  reg signed [31:0] AccReg_t_0_0;  // int32
  reg signed [31:0] AccReg_t_1;  // int32


  always @(posedge clk or posedge reset)
    begin : temp_process1_process
      if (reset == 1'b1) begin
        for(temp_process1_t_1_0 = 32'sd0; temp_process1_t_1_0 <= 32'sd14; temp_process1_t_1_0 = temp_process1_t_1_0 + 32'sd1) begin
          temp_process1_reg[temp_process1_t_1_0] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(temp_process1_t_0_1 = 32'sd0; temp_process1_t_0_1 <= 32'sd14; temp_process1_t_0_1 = temp_process1_t_0_1 + 32'sd1) begin
            temp_process1_reg[temp_process1_t_0_1] <= temp_process1_reg_next[temp_process1_t_0_1];
          end
        end
      end
    end

  always @* begin

    for(temp_process1_t_0_0 = 32'sd0; temp_process1_t_0_0 <= 32'sd14; temp_process1_t_0_0 = temp_process1_t_0_0 + 32'sd1) begin
      data_pipeline[temp_process1_t_0_0] = temp_process1_reg[temp_process1_t_0_0];
    end

    data_pipeline[15] = lms_input;

    for(temp_process1_t_1 = 32'sd0; temp_process1_t_1 <= 32'sd13; temp_process1_t_1 = temp_process1_t_1 + 32'sd1) begin
      temp_process1_reg_next[temp_process1_t_1] = temp_process1_reg[32'sd1 + temp_process1_t_1];
    end

    temp_process1_reg_next[14] = lms_input;
  end



  assign data_pipeline_0 = data_pipeline[0];

  assign data_pipeline_0_1 = data_pipeline[0];

  assign C_LMS_FILTER_STEP_SIZE = 16'sb0100000000000000;



  assign data_pipeline_1 = data_pipeline[1];

  assign data_pipeline_2 = data_pipeline[2];

  assign data_pipeline_3 = data_pipeline[3];

  assign data_pipeline_4 = data_pipeline[4];

  assign data_pipeline_5 = data_pipeline[5];

  assign data_pipeline_6 = data_pipeline[6];

  assign data_pipeline_7 = data_pipeline[7];

  assign data_pipeline_8 = data_pipeline[8];

  assign data_pipeline_9 = data_pipeline[9];

  assign data_pipeline_10 = data_pipeline[10];

  assign data_pipeline_11 = data_pipeline[11];

  assign data_pipeline_12 = data_pipeline[12];

  assign data_pipeline_13 = data_pipeline[13];

  assign data_pipeline_14 = data_pipeline[14];

  assign data_pipeline_15 = data_pipeline[15];

  assign data_pipeline_1_1 = data_pipeline[1];

  assign data_pipeline_2_1 = data_pipeline[2];

  assign data_pipeline_3_1 = data_pipeline[3];

  assign data_pipeline_4_1 = data_pipeline[4];

  assign data_pipeline_5_1 = data_pipeline[5];

  assign data_pipeline_6_1 = data_pipeline[6];

  assign data_pipeline_7_1 = data_pipeline[7];

  assign data_pipeline_8_1 = data_pipeline[8];

  assign data_pipeline_9_1 = data_pipeline[9];

  assign data_pipeline_10_1 = data_pipeline[10];

  assign data_pipeline_11_1 = data_pipeline[11];

  assign data_pipeline_12_1 = data_pipeline[12];

  assign data_pipeline_13_1 = data_pipeline[13];

  assign data_pipeline_14_1 = data_pipeline[14];

  assign data_pipeline_15_1 = data_pipeline[15];

  assign weight_15 = weight[15];

  assign multiplier_mul_temp = data_pipeline_15_1 * weight_15;
  assign filter_products_15 = multiplier_mul_temp[29:14] + $signed({1'b0, multiplier_mul_temp[13] & (multiplier_mul_temp[14] | (|multiplier_mul_temp[12:0]))});



  assign weight_14 = weight[14];

  assign multiplier_mul_temp_1 = data_pipeline_14_1 * weight_14;
  assign filter_products_14 = multiplier_mul_temp_1[29:14] + $signed({1'b0, multiplier_mul_temp_1[13] & (multiplier_mul_temp_1[14] | (|multiplier_mul_temp_1[12:0]))});



  assign weight_13 = weight[13];

  assign multiplier_mul_temp_2 = data_pipeline_13_1 * weight_13;
  assign filter_products_13 = multiplier_mul_temp_2[29:14] + $signed({1'b0, multiplier_mul_temp_2[13] & (multiplier_mul_temp_2[14] | (|multiplier_mul_temp_2[12:0]))});



  assign weight_12 = weight[12];

  assign multiplier_mul_temp_3 = data_pipeline_12_1 * weight_12;
  assign filter_products_12 = multiplier_mul_temp_3[29:14] + $signed({1'b0, multiplier_mul_temp_3[13] & (multiplier_mul_temp_3[14] | (|multiplier_mul_temp_3[12:0]))});



  assign weight_11 = weight[11];

  assign multiplier_mul_temp_4 = data_pipeline_11_1 * weight_11;
  assign filter_products_11 = multiplier_mul_temp_4[29:14] + $signed({1'b0, multiplier_mul_temp_4[13] & (multiplier_mul_temp_4[14] | (|multiplier_mul_temp_4[12:0]))});



  assign weight_10 = weight[10];

  assign multiplier_mul_temp_5 = data_pipeline_10_1 * weight_10;
  assign filter_products_10 = multiplier_mul_temp_5[29:14] + $signed({1'b0, multiplier_mul_temp_5[13] & (multiplier_mul_temp_5[14] | (|multiplier_mul_temp_5[12:0]))});



  assign weight_9 = weight[9];

  assign multiplier_mul_temp_6 = data_pipeline_9_1 * weight_9;
  assign filter_products_9 = multiplier_mul_temp_6[29:14] + $signed({1'b0, multiplier_mul_temp_6[13] & (multiplier_mul_temp_6[14] | (|multiplier_mul_temp_6[12:0]))});



  assign weight_8 = weight[8];

  assign multiplier_mul_temp_7 = data_pipeline_8_1 * weight_8;
  assign filter_products_8 = multiplier_mul_temp_7[29:14] + $signed({1'b0, multiplier_mul_temp_7[13] & (multiplier_mul_temp_7[14] | (|multiplier_mul_temp_7[12:0]))});



  assign weight_7 = weight[7];

  assign multiplier_mul_temp_8 = data_pipeline_7_1 * weight_7;
  assign filter_products_7 = multiplier_mul_temp_8[29:14] + $signed({1'b0, multiplier_mul_temp_8[13] & (multiplier_mul_temp_8[14] | (|multiplier_mul_temp_8[12:0]))});



  assign weight_6 = weight[6];

  assign multiplier_mul_temp_9 = data_pipeline_6_1 * weight_6;
  assign filter_products_6 = multiplier_mul_temp_9[29:14] + $signed({1'b0, multiplier_mul_temp_9[13] & (multiplier_mul_temp_9[14] | (|multiplier_mul_temp_9[12:0]))});



  assign weight_5 = weight[5];

  assign multiplier_mul_temp_10 = data_pipeline_5_1 * weight_5;
  assign filter_products_5 = multiplier_mul_temp_10[29:14] + $signed({1'b0, multiplier_mul_temp_10[13] & (multiplier_mul_temp_10[14] | (|multiplier_mul_temp_10[12:0]))});



  assign weight_4 = weight[4];

  assign multiplier_mul_temp_11 = data_pipeline_4_1 * weight_4;
  assign filter_products_4 = multiplier_mul_temp_11[29:14] + $signed({1'b0, multiplier_mul_temp_11[13] & (multiplier_mul_temp_11[14] | (|multiplier_mul_temp_11[12:0]))});



  assign weight_3 = weight[3];

  assign multiplier_mul_temp_12 = data_pipeline_3_1 * weight_3;
  assign filter_products_3 = multiplier_mul_temp_12[29:14] + $signed({1'b0, multiplier_mul_temp_12[13] & (multiplier_mul_temp_12[14] | (|multiplier_mul_temp_12[12:0]))});



  assign weight_2 = weight[2];

  assign multiplier_mul_temp_13 = data_pipeline_2_1 * weight_2;
  assign filter_products_2 = multiplier_mul_temp_13[29:14] + $signed({1'b0, multiplier_mul_temp_13[13] & (multiplier_mul_temp_13[14] | (|multiplier_mul_temp_13[12:0]))});



  assign weight_1 = weight[1];

  assign multiplier_mul_temp_14 = data_pipeline_1_1 * weight_1;
  assign filter_products_1 = multiplier_mul_temp_14[29:14] + $signed({1'b0, multiplier_mul_temp_14[13] & (multiplier_mul_temp_14[14] | (|multiplier_mul_temp_14[12:0]))});



  assign multiplier_mul_temp_15 = data_pipeline_15 * mu_err;
  assign mu_err_data_prod_15 = multiplier_mul_temp_15[29:14] + $signed({1'b0, multiplier_mul_temp_15[13] & (multiplier_mul_temp_15[14] | (|multiplier_mul_temp_15[12:0]))});



  assign weight_15_1 = weight[15];

  assign weight_adder_output_15 = weight_15_1 + mu_err_data_prod_15;



  assign multiplier_mul_temp_16 = data_pipeline_14 * mu_err;
  assign mu_err_data_prod_14 = multiplier_mul_temp_16[29:14] + $signed({1'b0, multiplier_mul_temp_16[13] & (multiplier_mul_temp_16[14] | (|multiplier_mul_temp_16[12:0]))});



  assign weight_14_1 = weight[14];

  assign weight_adder_output_14 = weight_14_1 + mu_err_data_prod_14;



  assign multiplier_mul_temp_17 = data_pipeline_13 * mu_err;
  assign mu_err_data_prod_13 = multiplier_mul_temp_17[29:14] + $signed({1'b0, multiplier_mul_temp_17[13] & (multiplier_mul_temp_17[14] | (|multiplier_mul_temp_17[12:0]))});



  assign weight_13_1 = weight[13];

  assign weight_adder_output_13 = weight_13_1 + mu_err_data_prod_13;



  assign multiplier_mul_temp_18 = data_pipeline_12 * mu_err;
  assign mu_err_data_prod_12 = multiplier_mul_temp_18[29:14] + $signed({1'b0, multiplier_mul_temp_18[13] & (multiplier_mul_temp_18[14] | (|multiplier_mul_temp_18[12:0]))});



  assign weight_12_1 = weight[12];

  assign weight_adder_output_12 = weight_12_1 + mu_err_data_prod_12;



  assign multiplier_mul_temp_19 = data_pipeline_11 * mu_err;
  assign mu_err_data_prod_11 = multiplier_mul_temp_19[29:14] + $signed({1'b0, multiplier_mul_temp_19[13] & (multiplier_mul_temp_19[14] | (|multiplier_mul_temp_19[12:0]))});



  assign weight_11_1 = weight[11];

  assign weight_adder_output_11 = weight_11_1 + mu_err_data_prod_11;



  assign multiplier_mul_temp_20 = data_pipeline_10 * mu_err;
  assign mu_err_data_prod_10 = multiplier_mul_temp_20[29:14] + $signed({1'b0, multiplier_mul_temp_20[13] & (multiplier_mul_temp_20[14] | (|multiplier_mul_temp_20[12:0]))});



  assign weight_10_1 = weight[10];

  assign weight_adder_output_10 = weight_10_1 + mu_err_data_prod_10;



  assign multiplier_mul_temp_21 = data_pipeline_9 * mu_err;
  assign mu_err_data_prod_9 = multiplier_mul_temp_21[29:14] + $signed({1'b0, multiplier_mul_temp_21[13] & (multiplier_mul_temp_21[14] | (|multiplier_mul_temp_21[12:0]))});



  assign weight_9_1 = weight[9];

  assign weight_adder_output_9 = weight_9_1 + mu_err_data_prod_9;



  assign multiplier_mul_temp_22 = data_pipeline_8 * mu_err;
  assign mu_err_data_prod_8 = multiplier_mul_temp_22[29:14] + $signed({1'b0, multiplier_mul_temp_22[13] & (multiplier_mul_temp_22[14] | (|multiplier_mul_temp_22[12:0]))});



  assign weight_8_1 = weight[8];

  assign weight_adder_output_8 = weight_8_1 + mu_err_data_prod_8;



  assign multiplier_mul_temp_23 = data_pipeline_7 * mu_err;
  assign mu_err_data_prod_7 = multiplier_mul_temp_23[29:14] + $signed({1'b0, multiplier_mul_temp_23[13] & (multiplier_mul_temp_23[14] | (|multiplier_mul_temp_23[12:0]))});



  assign weight_7_1 = weight[7];

  assign weight_adder_output_7 = weight_7_1 + mu_err_data_prod_7;



  assign multiplier_mul_temp_24 = data_pipeline_6 * mu_err;
  assign mu_err_data_prod_6 = multiplier_mul_temp_24[29:14] + $signed({1'b0, multiplier_mul_temp_24[13] & (multiplier_mul_temp_24[14] | (|multiplier_mul_temp_24[12:0]))});



  assign weight_6_1 = weight[6];

  assign weight_adder_output_6 = weight_6_1 + mu_err_data_prod_6;



  assign multiplier_mul_temp_25 = data_pipeline_5 * mu_err;
  assign mu_err_data_prod_5 = multiplier_mul_temp_25[29:14] + $signed({1'b0, multiplier_mul_temp_25[13] & (multiplier_mul_temp_25[14] | (|multiplier_mul_temp_25[12:0]))});



  assign weight_5_1 = weight[5];

  assign weight_adder_output_5 = weight_5_1 + mu_err_data_prod_5;



  assign multiplier_mul_temp_26 = data_pipeline_4 * mu_err;
  assign mu_err_data_prod_4 = multiplier_mul_temp_26[29:14] + $signed({1'b0, multiplier_mul_temp_26[13] & (multiplier_mul_temp_26[14] | (|multiplier_mul_temp_26[12:0]))});



  assign weight_4_1 = weight[4];

  assign weight_adder_output_4 = weight_4_1 + mu_err_data_prod_4;



  assign multiplier_mul_temp_27 = data_pipeline_3 * mu_err;
  assign mu_err_data_prod_3 = multiplier_mul_temp_27[29:14] + $signed({1'b0, multiplier_mul_temp_27[13] & (multiplier_mul_temp_27[14] | (|multiplier_mul_temp_27[12:0]))});



  assign weight_3_1 = weight[3];

  assign weight_adder_output_3 = weight_3_1 + mu_err_data_prod_3;



  assign multiplier_mul_temp_28 = data_pipeline_2 * mu_err;
  assign mu_err_data_prod_2 = multiplier_mul_temp_28[29:14] + $signed({1'b0, multiplier_mul_temp_28[13] & (multiplier_mul_temp_28[14] | (|multiplier_mul_temp_28[12:0]))});



  assign weight_2_1 = weight[2];

  assign weight_adder_output_2 = weight_2_1 + mu_err_data_prod_2;



  assign multiplier_mul_temp_29 = data_pipeline_1 * mu_err;
  assign mu_err_data_prod_1 = multiplier_mul_temp_29[29:14] + $signed({1'b0, multiplier_mul_temp_29[13] & (multiplier_mul_temp_29[14] | (|multiplier_mul_temp_29[12:0]))});



  assign weight_1_1 = weight[1];

  assign weight_adder_output_1 = weight_1_1 + mu_err_data_prod_1;



  assign multiplier_mul_temp_30 = C_LMS_FILTER_STEP_SIZE * filter_error_sub_accum;
  assign mu_err = ({multiplier_mul_temp_30[31], multiplier_mul_temp_30[31:17]}) + $signed({1'b0, multiplier_mul_temp_30[16] & (multiplier_mul_temp_30[17] | (|multiplier_mul_temp_30[15:0]))});



  assign multiplier_mul_temp_31 = data_pipeline_0_1 * mu_err;
  assign mu_err_data_prod_0 = multiplier_mul_temp_31[29:14] + $signed({1'b0, multiplier_mul_temp_31[13] & (multiplier_mul_temp_31[14] | (|multiplier_mul_temp_31[12:0]))});



  assign weight_0 = weight[0];

  assign weight_adder_output_0 = weight_0 + mu_err_data_prod_0;



  assign weight_adder_output[0] = weight_adder_output_0;
  assign weight_adder_output[1] = weight_adder_output_1;
  assign weight_adder_output[2] = weight_adder_output_2;
  assign weight_adder_output[3] = weight_adder_output_3;
  assign weight_adder_output[4] = weight_adder_output_4;
  assign weight_adder_output[5] = weight_adder_output_5;
  assign weight_adder_output[6] = weight_adder_output_6;
  assign weight_adder_output[7] = weight_adder_output_7;
  assign weight_adder_output[8] = weight_adder_output_8;
  assign weight_adder_output[9] = weight_adder_output_9;
  assign weight_adder_output[10] = weight_adder_output_10;
  assign weight_adder_output[11] = weight_adder_output_11;
  assign weight_adder_output[12] = weight_adder_output_12;
  assign weight_adder_output[13] = weight_adder_output_13;
  assign weight_adder_output[14] = weight_adder_output_14;
  assign weight_adder_output[15] = weight_adder_output_15;

  always @(posedge clk or posedge reset)
    begin : AccReg_process
      if (reset == 1'b1) begin
        for(AccReg_t_1 = 32'sd0; AccReg_t_1 <= 32'sd15; AccReg_t_1 = AccReg_t_1 + 32'sd1) begin
          weight[AccReg_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(AccReg_t_0_0 = 32'sd0; AccReg_t_0_0 <= 32'sd15; AccReg_t_0_0 = AccReg_t_0_0 + 32'sd1) begin
            weight[AccReg_t_0_0] <= weight_adder_output[AccReg_t_0_0];
          end
        end
      end
    end



  assign weight_0_1 = weight[0];

  assign multiplier_mul_temp_32 = data_pipeline_0 * weight_0_1;
  assign filter_products_0 = multiplier_mul_temp_32[29:14] + $signed({1'b0, multiplier_mul_temp_32[13] & (multiplier_mul_temp_32[14] | (|multiplier_mul_temp_32[12:0]))});



  assign fir_add_stage2_add_temp = filter_products_0 + filter_products_1;
  assign fir_add_op_stage1 = {fir_add_stage2_add_temp[15], fir_add_stage2_add_temp};



  assign fir_add_stage3_add_cast = fir_add_op_stage1[15:0];
  assign fir_add_stage3_add_temp = fir_add_stage3_add_cast + filter_products_2;
  assign fir_add_op_stage2 = {{2{fir_add_stage3_add_temp[15]}}, fir_add_stage3_add_temp};



  assign fir_add_stage4_add_cast = fir_add_op_stage2[15:0];
  assign fir_add_stage4_add_temp = fir_add_stage4_add_cast + filter_products_3;
  assign fir_add_op_stage3 = {{3{fir_add_stage4_add_temp[15]}}, fir_add_stage4_add_temp};



  assign fir_add_stage5_add_cast = fir_add_op_stage3[15:0];
  assign fir_add_stage5_add_temp = fir_add_stage5_add_cast + filter_products_4;
  assign fir_add_op_stage4 = {{4{fir_add_stage5_add_temp[15]}}, fir_add_stage5_add_temp};



  assign fir_add_stage6_add_cast = fir_add_op_stage4[15:0];
  assign fir_add_stage6_add_temp = fir_add_stage6_add_cast + filter_products_5;
  assign fir_add_op_stage5 = {{5{fir_add_stage6_add_temp[15]}}, fir_add_stage6_add_temp};



  assign fir_add_stage7_add_cast = fir_add_op_stage5[15:0];
  assign fir_add_stage7_add_temp = fir_add_stage7_add_cast + filter_products_6;
  assign fir_add_op_stage6 = {{6{fir_add_stage7_add_temp[15]}}, fir_add_stage7_add_temp};



  assign fir_add_stage8_add_cast = fir_add_op_stage6[15:0];
  assign fir_add_stage8_add_temp = fir_add_stage8_add_cast + filter_products_7;
  assign fir_add_op_stage7 = {{7{fir_add_stage8_add_temp[15]}}, fir_add_stage8_add_temp};



  assign fir_add_stage9_add_cast = fir_add_op_stage7[15:0];
  assign fir_add_stage9_add_temp = fir_add_stage9_add_cast + filter_products_8;
  assign fir_add_op_stage8 = {{8{fir_add_stage9_add_temp[15]}}, fir_add_stage9_add_temp};



  assign fir_add_stage10_add_cast = fir_add_op_stage8[15:0];
  assign fir_add_stage10_add_temp = fir_add_stage10_add_cast + filter_products_9;
  assign fir_add_op_stage9 = {{9{fir_add_stage10_add_temp[15]}}, fir_add_stage10_add_temp};



  assign fir_add_stage11_add_cast = fir_add_op_stage9[15:0];
  assign fir_add_stage11_add_temp = fir_add_stage11_add_cast + filter_products_10;
  assign fir_add_op_stage10 = {{10{fir_add_stage11_add_temp[15]}}, fir_add_stage11_add_temp};



  assign fir_add_stage12_add_cast = fir_add_op_stage10[15:0];
  assign fir_add_stage12_add_temp = fir_add_stage12_add_cast + filter_products_11;
  assign fir_add_op_stage11 = {{11{fir_add_stage12_add_temp[15]}}, fir_add_stage12_add_temp};



  assign fir_add_stage13_add_cast = fir_add_op_stage11[15:0];
  assign fir_add_stage13_add_temp = fir_add_stage13_add_cast + filter_products_12;
  assign fir_add_op_stage12 = {{12{fir_add_stage13_add_temp[15]}}, fir_add_stage13_add_temp};



  assign fir_add_stage14_add_cast = fir_add_op_stage12[15:0];
  assign fir_add_stage14_add_temp = fir_add_stage14_add_cast + filter_products_13;
  assign fir_add_op_stage13 = {{13{fir_add_stage14_add_temp[15]}}, fir_add_stage14_add_temp};



  assign fir_add_stage15_add_cast = fir_add_op_stage13[15:0];
  assign fir_add_stage15_add_temp = fir_add_stage15_add_cast + filter_products_14;
  assign fir_add_op_stage14 = {{14{fir_add_stage15_add_temp[15]}}, fir_add_stage15_add_temp};



  // linear sum of filter products
  assign fir_add_stage16_add_cast = fir_add_op_stage14[15:0];
  assign filter_sum = fir_add_stage16_add_cast + filter_products_15;



  // Calculate Filter Error
  assign filter_error_sub_accum = lms_desired - filter_sum;



  assign lms_error = filter_error_sub_accum;

endmodule  // lms_pcore_src_LMS_Filter

