// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\lms\lms_pcore_addr_decoder.v
// Created: 2026-06-05 20:55:59
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: lms_pcore_addr_decoder
// Source Path: lms_pcore/lms_pcore_axi_lite/lms_pcore_addr_decoder
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module lms_pcore_addr_decoder
          (clk,
           reset,
           data_write,
           addr_sel,
           wr_enb,
           rd_enb,
           read_cop_out_ready,
           read_ip_timestamp,
           cop_reg_strobe,
           read_e_k,
           data_read,
           write_axi_enable,
           strobe_cop_in_strobe,
           write_x_k,
           write_d_k);


  input   clk;
  input   reset;
  input   [31:0] data_write;  // ufix32
  input   [13:0] addr_sel;  // ufix14
  input   wr_enb;  // ufix1
  input   rd_enb;  // ufix1
  input   read_cop_out_ready;  // ufix1
  input   [31:0] read_ip_timestamp;  // ufix32
  input   cop_reg_strobe;  // ufix1
  input   signed [15:0] read_e_k;  // sfix16_En14
  output  [31:0] data_read;  // ufix32
  output  write_axi_enable;  // ufix1
  output  strobe_cop_in_strobe;  // ufix1
  output  signed [15:0] write_x_k;  // sfix16_En14
  output  signed [15:0] write_d_k;  // sfix16_En14


  wire enb;
  wire decode_sel_cop_out_ready_1_1;  // ufix1
  wire const_1;  // ufix1
  wire decode_sel_ip_timestamp_1_1;  // ufix1
  wire [31:0] const_0;  // ufix32
  reg  read_reg_cop_out_ready;  // ufix1
  wire [31:0] data_slice_cop_out_ready_1;  // ufix32
  wire [31:0] decode_rd_cop_out_ready_1_1;  // ufix32
  wire decode_sel_e_k_1_1;  // ufix1
  reg [31:0] read_reg_ip_timestamp;  // ufix32
  wire [31:0] decode_rd_ip_timestamp_1_1;  // ufix32
  reg signed [15:0] sync_reg_e_k;  // sfix16_En14
  wire [31:0] data_slice_e_k_1;  // ufix32
  wire [31:0] decode_rd_e_k_1_1;  // ufix32
  wire decode_sel_axi_enable_1_1;  // ufix1
  wire reg_enb_axi_enable_1_1;  // ufix1
  wire data_in_axi_enable;  // ufix1
  reg  data_reg_axi_enable_1_1;  // ufix1
  wire decode_sel_cop_in_strobe;  // ufix1
  wire strobe_sel_cop_in_strobe;  // ufix1
  wire const_zero;  // ufix1
  wire strobe_in_cop_in_strobe;  // ufix1
  wire strobe_sw_cop_in_strobe;  // ufix1
  reg  strobe_reg_cop_in_strobe;  // ufix1
  wire decode_sel_x_k_1_1;  // ufix1
  wire reg_enb_x_k_1_1;  // ufix1
  wire signed [15:0] data_in_x_k;  // sfix16_En14
  reg signed [15:0] data_reg_x_k_1_1;  // sfix16_En14
  wire decode_sel_d_k_1_1;  // ufix1
  wire reg_enb_d_k_1_1;  // ufix1
  wire signed [15:0] data_in_d_k;  // sfix16_En14
  reg signed [15:0] data_reg_d_k_1_1;  // sfix16_En14


  assign decode_sel_cop_out_ready_1_1 = addr_sel == 14'b00000000000011;



  assign const_1 = 1'b1;



  assign enb = const_1;

  assign decode_sel_ip_timestamp_1_1 = addr_sel == 14'b00000000000100;



  assign const_0 = 32'b00000000000000000000000000000000;



  always @(posedge clk or posedge reset)
    begin : reg_cop_out_ready_process
      if (reset == 1'b1) begin
        read_reg_cop_out_ready <= 1'b0;
      end
      else begin
        if (enb) begin
          read_reg_cop_out_ready <= read_cop_out_ready;
        end
      end
    end



  assign data_slice_cop_out_ready_1 = {31'b0, read_reg_cop_out_ready};



  assign decode_rd_cop_out_ready_1_1 = (decode_sel_cop_out_ready_1_1 == 1'b0 ? const_0 :
              data_slice_cop_out_ready_1);



  assign decode_sel_e_k_1_1 = addr_sel == 14'b00000001000010;



  always @(posedge clk or posedge reset)
    begin : reg_ip_timestamp_process
      if (reset == 1'b1) begin
        read_reg_ip_timestamp <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          read_reg_ip_timestamp <= read_ip_timestamp;
        end
      end
    end



  assign decode_rd_ip_timestamp_1_1 = (decode_sel_ip_timestamp_1_1 == 1'b0 ? decode_rd_cop_out_ready_1_1 :
              read_reg_ip_timestamp);



  always @(posedge clk or posedge reset)
    begin : reg_e_k_process
      if (reset == 1'b1) begin
        sync_reg_e_k <= 16'sb0000000000000000;
      end
      else begin
        if (enb && cop_reg_strobe) begin
          sync_reg_e_k <= read_e_k;
        end
      end
    end



  assign data_slice_e_k_1 = {{16{sync_reg_e_k[15]}}, sync_reg_e_k};



  assign decode_rd_e_k_1_1 = (decode_sel_e_k_1_1 == 1'b0 ? decode_rd_ip_timestamp_1_1 :
              data_slice_e_k_1);



  assign data_read = decode_rd_e_k_1_1;

  assign decode_sel_axi_enable_1_1 = addr_sel == 14'b00000000000001;



  assign reg_enb_axi_enable_1_1 = decode_sel_axi_enable_1_1 & wr_enb;



  assign data_in_axi_enable = data_write[0];



  always @(posedge clk or posedge reset)
    begin : reg_axi_enable_1_1_process
      if (reset == 1'b1) begin
        data_reg_axi_enable_1_1 <= 1'b1;
      end
      else begin
        if (enb && reg_enb_axi_enable_1_1) begin
          data_reg_axi_enable_1_1 <= data_in_axi_enable;
        end
      end
    end



  assign write_axi_enable = data_reg_axi_enable_1_1;

  assign decode_sel_cop_in_strobe = addr_sel == 14'b00000000000010;



  assign strobe_sel_cop_in_strobe = decode_sel_cop_in_strobe & wr_enb;



  assign const_zero = 1'b0;



  assign strobe_in_cop_in_strobe = data_write[0];



  assign strobe_sw_cop_in_strobe = (strobe_sel_cop_in_strobe == 1'b0 ? const_zero :
              strobe_in_cop_in_strobe);



  always @(posedge clk or posedge reset)
    begin : reg_rsvd_process
      if (reset == 1'b1) begin
        strobe_reg_cop_in_strobe <= 1'b0;
      end
      else begin
        if (enb) begin
          strobe_reg_cop_in_strobe <= strobe_sw_cop_in_strobe;
        end
      end
    end



  assign strobe_cop_in_strobe = strobe_reg_cop_in_strobe;

  assign decode_sel_x_k_1_1 = addr_sel == 14'b00000001000000;



  assign reg_enb_x_k_1_1 = decode_sel_x_k_1_1 & wr_enb;



  assign data_in_x_k = $signed(data_write[15:0]);



  always @(posedge clk or posedge reset)
    begin : reg_x_k_1_1_process
      if (reset == 1'b1) begin
        data_reg_x_k_1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb && reg_enb_x_k_1_1) begin
          data_reg_x_k_1_1 <= data_in_x_k;
        end
      end
    end



  assign write_x_k = data_reg_x_k_1_1;

  assign decode_sel_d_k_1_1 = addr_sel == 14'b00000001000001;



  assign reg_enb_d_k_1_1 = decode_sel_d_k_1_1 & wr_enb;



  assign data_in_d_k = $signed(data_write[15:0]);



  always @(posedge clk or posedge reset)
    begin : reg_d_k_1_1_process
      if (reset == 1'b1) begin
        data_reg_d_k_1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb && reg_enb_d_k_1_1) begin
          data_reg_d_k_1_1 <= data_in_d_k;
        end
      end
    end



  assign write_d_k = data_reg_d_k_1_1;

endmodule  // lms_pcore_addr_decoder

