// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\lms\lms_pcore_dut.v
// Created: 2026-06-05 20:55:59
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: lms_pcore_dut
// Source Path: lms_pcore/lms_pcore_dut
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module lms_pcore_dut
          (clk,
           reset,
           dut_enable,
           x_k,
           d_k,
           ce_out,
           e_k);


  input   clk;
  input   reset;
  input   dut_enable;  // ufix1
  input   signed [15:0] x_k;  // sfix16_En14
  input   signed [15:0] d_k;  // sfix16_En14
  output  ce_out;  // ufix1
  output  signed [15:0] e_k;  // sfix16_En14


  wire enb;
  wire ce_out_sig;  // ufix1
  wire signed [15:0] e_k_sig;  // sfix16_En14


  assign enb = dut_enable;

  lms_pcore_src_LMS u_lms_pcore_src_LMS (.clk(clk),
                                         .clk_enable(enb),
                                         .reset(reset),
                                         .x_k(x_k),  // sfix16_En14
                                         .d_k(d_k),  // sfix16_En14
                                         .ce_out(ce_out_sig),  // ufix1
                                         .e_k(e_k_sig)  // sfix16_En14
                                         );

  assign ce_out = ce_out_sig;

  assign e_k = e_k_sig;

endmodule  // lms_pcore_dut

