// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\lms\lms_pcore.v
// Created: 2026-06-05 20:55:59
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: -1
// Target subsystem base rate: -1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: lms_pcore
// Source Path: lms_pcore
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module lms_pcore
          (IPCORE_CLK,
           IPCORE_RESETN,
           AXI4_Lite_ACLK,
           AXI4_Lite_ARESETN,
           AXI4_Lite_AWADDR,
           AXI4_Lite_AWVALID,
           AXI4_Lite_WDATA,
           AXI4_Lite_WSTRB,
           AXI4_Lite_WVALID,
           AXI4_Lite_BREADY,
           AXI4_Lite_ARADDR,
           AXI4_Lite_ARVALID,
           AXI4_Lite_RREADY,
           AXI4_Lite_AWREADY,
           AXI4_Lite_WREADY,
           AXI4_Lite_BRESP,
           AXI4_Lite_BVALID,
           AXI4_Lite_ARREADY,
           AXI4_Lite_RDATA,
           AXI4_Lite_RRESP,
           AXI4_Lite_RVALID);


  input   IPCORE_CLK;  // ufix1
  input   IPCORE_RESETN;  // ufix1
  input   AXI4_Lite_ACLK;  // ufix1
  input   AXI4_Lite_ARESETN;  // ufix1
  input   [15:0] AXI4_Lite_AWADDR;  // ufix16
  input   AXI4_Lite_AWVALID;  // ufix1
  input   [31:0] AXI4_Lite_WDATA;  // ufix32
  input   [3:0] AXI4_Lite_WSTRB;  // ufix4
  input   AXI4_Lite_WVALID;  // ufix1
  input   AXI4_Lite_BREADY;  // ufix1
  input   [15:0] AXI4_Lite_ARADDR;  // ufix16
  input   AXI4_Lite_ARVALID;  // ufix1
  input   AXI4_Lite_RREADY;  // ufix1
  output  AXI4_Lite_AWREADY;  // ufix1
  output  AXI4_Lite_WREADY;  // ufix1
  output  [1:0] AXI4_Lite_BRESP;  // ufix2
  output  AXI4_Lite_BVALID;  // ufix1
  output  AXI4_Lite_ARREADY;  // ufix1
  output  [31:0] AXI4_Lite_RDATA;  // ufix32
  output  [1:0] AXI4_Lite_RRESP;  // ufix2
  output  AXI4_Lite_RVALID;  // ufix1


  wire reset;
  wire reset_cm;  // ufix1
  wire [31:0] ip_timestamp;  // ufix32
  wire cop_dut_enable;  // ufix1
  wire signed [15:0] write_x_k;  // sfix16_En14
  wire signed [15:0] write_d_k;  // sfix16_En14
  wire ce_out_sig;  // ufix1
  wire signed [15:0] e_k_sig;  // sfix16_En14
  wire reset_internal;  // ufix1
  wire reset_before_sync;  // ufix1
  wire strobe_cop_in_strobe;  // ufix1
  wire write_axi_enable;  // ufix1
  wire cop_out_ready;  // ufix1
  wire cop_reg_strobe;  // ufix1


  assign reset_cm =  ~ IPCORE_RESETN;



  assign ip_timestamp = 32'b10011011010101010011001011010111;



  lms_pcore_dut u_lms_pcore_dut_inst (.clk(IPCORE_CLK),  // ufix1
                                      .reset(reset),
                                      .dut_enable(cop_dut_enable),  // ufix1
                                      .x_k(write_x_k),  // sfix16_En14
                                      .d_k(write_d_k),  // sfix16_En14
                                      .ce_out(ce_out_sig),  // ufix1
                                      .e_k(e_k_sig)  // sfix16_En14
                                      );

  assign reset_before_sync = reset_cm | reset_internal;



  lms_pcore_reset_sync u_lms_pcore_reset_sync_inst (.clk(IPCORE_CLK),  // ufix1
                                                    .reset_in(reset_before_sync),  // ufix1
                                                    .reset_out(reset)
                                                    );

  lms_pcore_cop u_lms_pcore_cop_inst (.clk(IPCORE_CLK),  // ufix1
                                      .reset(reset),
                                      .in_strobe(strobe_cop_in_strobe),  // ufix1
                                      .cop_enable(write_axi_enable),  // ufix1
                                      .out_ready(cop_out_ready),  // ufix1
                                      .dut_enable(cop_dut_enable),  // ufix1
                                      .reg_strobe(cop_reg_strobe)  // ufix1
                                      );

  lms_pcore_axi_lite u_lms_pcore_axi_lite_inst (.reset(reset),
                                                .AXI4_Lite_ACLK(AXI4_Lite_ACLK),  // ufix1
                                                .AXI4_Lite_ARESETN(AXI4_Lite_ARESETN),  // ufix1
                                                .AXI4_Lite_AWADDR(AXI4_Lite_AWADDR),  // ufix16
                                                .AXI4_Lite_AWVALID(AXI4_Lite_AWVALID),  // ufix1
                                                .AXI4_Lite_WDATA(AXI4_Lite_WDATA),  // ufix32
                                                .AXI4_Lite_WSTRB(AXI4_Lite_WSTRB),  // ufix4
                                                .AXI4_Lite_WVALID(AXI4_Lite_WVALID),  // ufix1
                                                .AXI4_Lite_BREADY(AXI4_Lite_BREADY),  // ufix1
                                                .AXI4_Lite_ARADDR(AXI4_Lite_ARADDR),  // ufix16
                                                .AXI4_Lite_ARVALID(AXI4_Lite_ARVALID),  // ufix1
                                                .AXI4_Lite_RREADY(AXI4_Lite_RREADY),  // ufix1
                                                .read_cop_out_ready(cop_out_ready),  // ufix1
                                                .read_ip_timestamp(ip_timestamp),  // ufix32
                                                .cop_reg_strobe(strobe_cop_in_strobe),  // ufix1
                                                .read_e_k(e_k_sig),  // sfix16_En14
                                                .AXI4_Lite_AWREADY(AXI4_Lite_AWREADY),  // ufix1
                                                .AXI4_Lite_WREADY(AXI4_Lite_WREADY),  // ufix1
                                                .AXI4_Lite_BRESP(AXI4_Lite_BRESP),  // ufix2
                                                .AXI4_Lite_BVALID(AXI4_Lite_BVALID),  // ufix1
                                                .AXI4_Lite_ARREADY(AXI4_Lite_ARREADY),  // ufix1
                                                .AXI4_Lite_RDATA(AXI4_Lite_RDATA),  // ufix32
                                                .AXI4_Lite_RRESP(AXI4_Lite_RRESP),  // ufix2
                                                .AXI4_Lite_RVALID(AXI4_Lite_RVALID),  // ufix1
                                                .write_axi_enable(write_axi_enable),  // ufix1
                                                .strobe_cop_in_strobe(strobe_cop_in_strobe),  // ufix1
                                                .write_x_k(write_x_k),  // sfix16_En14
                                                .write_d_k(write_d_k),  // sfix16_En14
                                                .reset_internal(reset_internal)  // ufix1
                                                );

endmodule  // lms_pcore

