// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\lms\lms_pcore_src_LMS.v
// Created: 2026-06-05 20:55:49
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 2.26757e-05
// Target subsystem base rate: 2.26757e-05
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        2.26757e-05
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// e_k                           ce_out        2.26757e-05
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: lms_pcore_src_LMS
// Source Path: lms/LMS
// Hierarchy Level: 0
// Model version: 1.9
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module lms_pcore_src_LMS
          (clk,
           reset,
           clk_enable,
           x_k,
           d_k,
           ce_out,
           e_k);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [15:0] x_k;  // sfix16_En14
  input   signed [15:0] d_k;  // sfix16_En14
  output  ce_out;
  output  signed [15:0] e_k;  // sfix16_En14


  wire signed [15:0] LMS_Filter_out2;  // sfix16_En14


  lms_pcore_src_LMS_Filter u_LMS_Filter (.clk(clk),
                                         .reset(reset),
                                         .enb(clk_enable),
                                         .lms_input(x_k),  // sfix16_En14
                                         .lms_desired(d_k),  // sfix16_En14
                                         .lms_error(LMS_Filter_out2)  // sfix16_En14
                                         );

  assign e_k = LMS_Filter_out2;

  assign ce_out = clk_enable;

endmodule  // lms_pcore_src_LMS

